# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.13.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env: 
      DATABASE_URL: ${{DATABASE_URL}}
      NEXTAUTH_SECRET: ${{NEXTAUTH_SECRET}}
      CLOUDINARY_URL: ${{CLOUDINARY_URL}}
      NEXTAUTH_URL: ${{NEXTAUTH_URL}}
      GOOGLE_APP_PASSWORD: ${{GOOGLE_APP_PASSWORD}}
      GOOGLE_EMAIL: ${{GOOGLE_EMAIL}}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Building the website
      run: npm run build --if-present
    - name: cd into project dir
      run: cd /home/antareja/actions-runner/sources/antareja/antareja
