# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.13.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: create env file
      run: >
        touch .env.local
        echo DATABASE_URL=${{secrets.DATABASE_URL}} >> .env.local
        echo NEXTAUTH_SECRET=${{secrets.NEXTAUTH_SECRET}} >> .env.local
        echo CLOUDINARY_URL=${{secrets.CLOUDINARY_URL}} >> .env.local
        echo NEXTAUTH_URL=${{secrets.NEXTAUTH_URL}} >> .env.local
        echo GOOGLE_APP_PASSWORD=${{secrets.GOOGLE_APP_PASSWORD}} >> .env.local
        echo GOOGLE_EMAIL=${{secrets.GOOGLE_EMAIL}} >> .env.local
    - name: Building the website
      run: npm run build --if-present
    - name: cd into project dir
      run: cd /home/antareja/actions-runner/sources/antareja/antareja
