# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.13.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
      CLOUDINARY_URL: ${{secrets.CLOUDINARY_URL}}
      NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
      GOOGLE_APP_PASSWORD: ${{secrets.GOOGLE_APP_PASSWORD}}
      GOOGLE_EMAIL: ${{secrets.GOOGLE_EMAIL}}
    steps:
    - name: Installing packages
      run: npm ci
    - name: Building the website
      run: npm run build --if-present
    - name: cd into project dir
      run: cd /home/antareja/actions-runner/sources/antareja/antareja
